Bump rubocop gems
Updates rubocop.yml to account for these cops being renamed:

    .rubocop.yml: Lint/BlockAlignment has the wrong namespace - should be Layout
    .rubocop.yml: Lint/DefEndAlignment has the wrong namespace - should be Layout
    .rubocop.yml: Lint/EndAlignment has the wrong namespace - should be Layout
    .rubocop.yml: Style/AccessorMethodName has the wrong namespace - should be Naming
    .rubocop.yml: Style/ClassAndModuleCamelCase has the wrong namespace - should be Naming
    .rubocop.yml: Style/ConstantName has the wrong namespace - should be Naming
    .rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
    .rubocop.yml: Style/VariableName has the wrong namespace - should be Naming
    .rubocop.yml: Style/FileName has the wrong namespace - should be Naming
    .rubocop.yml: Style/MethodName has the wrong namespace - should be Naming
    .rubocop.yml: Style/PredicateName has the wrong namespace - should be Naming
    .rubocop.yml: GetText/DecorateFunctionMessage has the wrong namespace - should be I18n/GetText
    Error: Ambiguous cop name `GetText/DecorateString` used in /home/josh/work/puppet/.rubocop.yml
    needs department qualifier. Did you mean I18n/GetText/DecorateString or I18n/RailsI18n/DecorateString?

Converts scope.rb to based on CaseLikeIf cop, otherwise rubocop fails.

Removes `ext/suse/puppet.spec` from the exclude list.