PUP-9154 WIP
$ bx rspec ./spec/unit/http/service/compiler_spec.rb:27
Run options:
  include {:locations=>{"./spec/unit/http/service/compiler_spec.rb"=>[27]}}
  exclude {:benchmark=>true}
F

Failures:

  1) Puppet::HTTP::Service::Compiler when making requests includes default HTTP headers
     Failure/Error: raise Puppet::HTTP::SerializationError.new("Failed to deserialize #{model} from #{formatter.name}: #{err.message}", err)

     Puppet::HTTP::SerializationError:
       Failed to deserialize Puppet::Resource::Catalog from json: undefined method `[]' for #<Puppet::Resource::Catalog:0x00007fb36da27f38 @in_to={}, @out_from={}, @upstream_from={}, @downstream_from={}, @name=nil, @catalog_uuid="b18bbe61-477f-4ce5-9712-7d3f371cfddf", @catalog_format=2, @metadata={}, @recursive_metadata={}, @classes=[], @resource_table={}, @resources=[], @relationship_graph=nil, @host_config=true, @environment_instance=<Puppet::Node::Environment::None:8960 @name="none" @manifest="no_manifest" @modulepath="" >, @environment="none", @code_id=nil, @aliases={}>

           vertices = hash['vertices']
                          ^^^^^^^^^^^^
     # ./lib/puppet/http/service.rb:159:in `rescue in deserialize'
     # ./lib/puppet/http/service.rb:156:in `deserialize'
     # ./lib/puppet/http/service/compiler.rb:130:in `post_catalog'
     # ./spec/unit/http/service/compiler_spec.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:180:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `[]' for #<Puppet::Resource::Catalog:0x00007fb36da27f38 @in_to={}, @out_from={}, @upstream_from={}, @downstream_from={}, @name=nil, @catalog_uuid="b18bbe61-477f-4ce5-9712-7d3f371cfddf", @catalog_format=2, @metadata={}, @recursive_metadata={}, @classes=[], @resource_table={}, @resources=[], @relationship_graph=nil, @host_config=true, @environment_instance=<Puppet::Node::Environment::None:8960 @name="none" @manifest="no_manifest" @modulepath="" >, @environment="none", @code_id=nil, @aliases={}>
     #
     #       vertices = hash['vertices']
     #                      ^^^^^^^^^^^^
     #   ./lib/puppet/graph/simple_graph.rb:502:in `initialize_from_hash'